apiVersion: v1
kind: Service
metadata:
  name: notifications-api
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: notifications-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
